using Test
using Asap
using AsapToolkit

#=
First test suite for AsapToolkit, written alongside the Asap v1.0 port.
Smoke tests (constructors run, models solve) plus sanity checks
(global equilibrium, displacement recovery, section conversion).
=#

"Sum of all applied external forces [Fx, Fy, Fz] on a model."
function total_applied(model::Model)
    F = zeros(3)
    for load in model.loads
        if load isa NodeForce
            F .+= Vector(load.value)
        elseif load isa DistributedLoad
            #uniform full-span loads (as generated by LineLoad)
            F .+= Vector(load.direction) .* (first(load.w) * length(load.element))
        end
    end
    return F
end

"Sum of reactions along global direction `i` (1 = X, 2 = Y, 3 = Z)."
reaction_sum(model::Model, i::Integer) = sum(model.results.reactions[i:6:end])

"Test static global equilibrium in direction `i`."
function test_equilibrium(model::Model, i::Integer)
    F = total_applied(model)
    @test isapprox(reaction_sum(model, i), -F[i]; rtol = 1e-8)
end

#a basic frame section (kN-m-ish units)
const mat = Material(200e6, 77e6, 80., 0.3)
const frame_section = Section(mat, 1e-2, 1e-4, 5e-5, 1e-6)
const truss_section = Section(mat, 1e-3)

@testset "AsapToolkit" begin

    @testset "Warren2D" begin
        gen = Warren2D(7, 1.5, 1.2, truss_section)
        @test gen.model isa Model{Float64}
        @test !isnothing(gen.model.results)
        test_equilibrium(gen.model, 2)

        #NOTE: the vector-input Warren2D method is not tested — it references
        #undefined variables (`dx`, `dy`) in its final line and was broken
        #before the v1.0 port.
    end

    @testset "Pratt2D" begin
        gen = Pratt2D(12., 6, 1.5, truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 2)
    end

    @testset "BakerTruss" begin
        gen = BakerTruss(4, 1.0, 1.0, truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 2)
    end

    @testset "TrussFrame" begin
        gen = TrussFrame(6, 1.0, 3, 1.0, truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 2)
    end

    @testset "SpaceFrame" begin
        gen = SpaceFrame(4, 1.0, 4, 1.0, 1.0, truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 3)
    end

    @testset "SpaceFrameBeam" begin
        gen = SpaceFrameBeam(4, 1.0, 1.0, 1.0, truss_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 3)
    end

    @testset "Frame" begin
        gen = Frame(2, 6., 2, 5., 2, 4., 2., frame_section, frame_section, frame_section, frame_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 3)

        #generated index sets are consistent
        n_nodes = length(gen.model.nodes)
        @test all(1 .<= gen.iExteriorXnodes .<= n_nodes)
        @test all(1 .<= gen.iExteriorYnodes .<= n_nodes)
    end

    @testset "GridFrame" begin
        gen = GridFrame(6., 4, 6., 4, frame_section)
        @test gen.model isa Model{Float64}
        test_equilibrium(gen.model, 3)
    end

    @testset "GridNetwork (FDM)" begin
        gen = GridNetwork(4, 6., 4, 6.)
        @test gen.network isa Asap.Network
        @test gen.network.processed
    end

    @testset "Ground structures" begin
        gs = XGroundStructure(4., 4, 4., 4)
        truss = to_truss(gs, truss_section; load = [1., 0., 0.])
        @test truss isa Model{Float64}
        test_equilibrium(truss, 1)

        frame = to_frame(gs, frame_section)
        @test frame isa Model{Float64}
        test_equilibrium(frame, 3)
    end

    @testset "Geo" begin
        truss_gen = Pratt2D(12., 6, 1.5, truss_section)
        geo = Geo(truss_gen.model)
        @test geo isa ModelGeo
        @test length(geo.nodes) == length(truss_gen.model.nodes)
        @test length(geo.lengths) == length(truss_gen.model.elements)

        tgeo = TrussGeo(truss_gen.model)
        @test tgeo isa TrussGeo
        @test length(tgeo.forces) == length(truss_gen.model.elements)
        @test tgeo.max_abs_force > 0

        frame_gen = GridFrame(6., 4, 6., 4, frame_section)
        fgeo = Geo(frame_gen.model)
        @test fgeo isa ModelGeo
        @test fgeo.max_abs_My > 0
    end

    @testset "ElementDisplacements" begin
        #cantilever with tip load
        n1 = Node([0., 0., 0.], :fixed)
        n2 = Node([2., 0., 0.], :free, :tip)
        el = FrameElement(n1, n2, frame_section)
        load = NodeForce(n2, [0., 0., -10.])

        model = Model([n1, n2], [el], [load])
        solve!(model)

        ed = ElementDisplacements(el, model; resolution = 11)

        @test size(ed.uglobal) == (3, 11)
        @test ed.uglobal[:, 1] ≈ zeros(3) atol = 1e-12

        #sampled shape at t = 1 matches the tip nodal displacement
        utip = Vector(displacement(model.results, n2)[1:3])
        @test isapprox(ed.uglobal[:, end], utip; rtol = 1e-8)

        #base positions run along the element
        @test ed.basepositions[:, 1] ≈ Vector(n1.position)
        @test ed.basepositions[:, end] ≈ Vector(n2.position)

        #all-element sampling
        eds = displacements(model, 0.5)
        @test length(eds) == length(model.elements)

        #truss version: linear interpolation of end displacements
        truss_gen = Pratt2D(12., 6, 1.5, truss_section)
        tel = truss_gen.model.elements[1]
        ted = ElementDisplacements(tel, truss_gen.model; resolution = 5)
        tu2 = Vector(displacement(truss_gen.model.results, tel.nodeEnd)[1:3])
        @test isapprox(ted.uglobal[:, end], tu2; rtol = 1e-8)
    end

    @testset "FDM translations" begin
        truss_gen = Pratt2D(12., 6, 1.5, truss_section)
        network = to_network(truss_gen.model)
        @test network isa Asap.Network
        @test network.processed
        @test length(network.elements) == length(truss_gen.model.elements)

        truss_back = to_truss(network, truss_section)
        @test truss_back isa Model{Float64}
        @test !isnothing(truss_back.results)
    end

    @testset "SteelSections" begin
        w = W(String(first(Wnames)))
        @test w.A > 0

        fsec = toASAPframe(w, 200., 77.)
        @test fsec isa Section
        @test EA(fsec) > 0
        @test EIx(fsec) > 0
        @test GJ(fsec) > 0

        tsec = toASAPtruss(w, 200.)
        @test tsec isa Section
        @test EA(tsec) > 0
    end

    @testset "IO" begin
        truss_gen = Pratt2D(12., 6, 1.5, truss_section)

        topo = AsapToolkit.topologize(truss_gen.model)
        @test topo isa Dict
        @test length(topo["iStart"]) == length(truss_gen.model.elements)

        dir = mktempdir()
        fname = joinpath(dir, "ghtest")
        GHsave(truss_gen.model, fname)
        @test isfile(fname * ".json")

        frame_gen = GridFrame(6., 4, 6., 4, frame_section)
        fname2 = joinpath(dir, "ghframe")
        GHsave(frame_gen.model, fname2)
        @test isfile(fname2 * ".json")
    end

    @testset "General" begin
        gen = Pratt2D(12., 6, 1.5, truss_section)
        Cel = element_connectivity(gen.model)
        n_el = length(gen.model.elements)
        @test size(Cel) == (n_el, n_el)
        @test Cel == Cel'
    end

end
